services:
  counter:
  #To start a multiple instances of this srevice, run command:
  #'docker compose up --scale counter=N', N=number of instances
  #and then 'docker compose ps' to list the port mappings
    image: counter:latest
    build:
      context: .
      dockerfile: Dockerfile
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx-configs/round-robin.conf:/etc/nginx/nginx.conf
    depends_on:
      - counter
    ports:
      - "4000:4000"