services:
  counter:
  #To start a multiple instances of this srevice, run command:
  #'docker compose up --scale counter=N', N=number of instances
  #and then 'docker compose ps' to list the port mappings
    image: counter:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080"