apiVersion: v1
kind: Deployment
metadata:
  name: k8s-example
spec:
  selector:
    matchLabels:
      app: k8s-example
  replicas: 3
  template:
    metadata:
      lables:
        app: k8s-example
    spec:
      containers:
        - name: counter
          image: counter:latest
          imagePullPolicy: IfNotPresent
        - name: nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
        - name: redis
          image: redis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379